"""
Send the portfolio report as a styled HTML email via Gmail SMTP.
"""

import os
import ssl
import logging
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import markdown

logger = logging.getLogger(__name__)

# ── HTML email template ──────────────────────────────────────────
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body {{
    margin: 0; padding: 0;
    font-family: Georgia, 'Times New Roman', serif;
    background: #f4f4f4; color: #222;
    line-height: 1.7;
  }}
  .wrapper {{
    max-width: 860px; margin: 0 auto;
    background: #ffffff;
    border: 1px solid #ddd;
  }}
  .header {{
    background: #1a3c2e; color: #ffffff;
    padding: 28px 32px;
  }}
  .header h1 {{
    margin: 0; font-size: 24px; font-weight: 700;
    letter-spacing: 0.5px;
  }}
  .header .subtitle {{
    margin-top: 4px; font-size: 14px; opacity: 0.85;
  }}
  .summary-bar {{
    background: #f0f7f4; padding: 16px 32px;
    display: flex; gap: 24px; flex-wrap: wrap;
    border-bottom: 2px solid #1a3c2e;
    font-family: 'Helvetica Neue', Arial, sans-serif;
  }}
  .summary-bar .metric {{
    font-size: 13px; color: #555;
  }}
  .summary-bar .metric .value {{
    font-size: 20px; font-weight: 700; display: block;
    color: #1a3c2e;
  }}
  .badge-green {{
    color: #0d6e3d; background: #d4edda;
    padding: 2px 8px; border-radius: 4px;
    font-weight: 700;
  }}
  .badge-red {{
    color: #842029; background: #f8d7da;
    padding: 2px 8px; border-radius: 4px;
    font-weight: 700;
  }}
  .content {{
    padding: 24px 32px 40px;
  }}
  .content h1, .content h2, .content h3 {{
    color: #1a3c2e;
    border-bottom: 2px solid #e0e0e0;
    padding-bottom: 6px;
    margin-top: 32px;
  }}
  .content h1 {{ font-size: 22px; }}
  .content h2 {{ font-size: 18px; }}
  .content h3 {{ font-size: 16px; border-bottom: none; }}
  table {{
    width: 100%; border-collapse: collapse;
    margin: 16px 0; font-size: 14px;
    font-family: 'Helvetica Neue', Arial, sans-serif;
  }}
  th {{
    background: #1a3c2e; color: #fff;
    text-align: left; padding: 8px 10px;
  }}
  td {{
    padding: 7px 10px; border-bottom: 1px solid #e8e8e8;
  }}
  tr:nth-child(even) td {{
    background: #fafafa;
  }}
  code, pre {{
    background: #f5f5f5; padding: 2px 6px;
    border-radius: 3px; font-size: 13px;
    font-family: 'SF Mono', Menlo, monospace;
  }}
  pre {{
    padding: 12px; overflow-x: auto;
  }}
  .footer {{
    background: #f8f8f8; padding: 16px 32px;
    font-size: 12px; color: #999;
    text-align: center;
    border-top: 1px solid #e0e0e0;
    font-family: Arial, sans-serif;
  }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>📊 Monthly Portfolio Review — {month_year}</h1>
    <div class="subtitle">Auto-generated on {generated_at}</div>
  </div>

  <div class="summary-bar">
    <div class="metric">
      Current Value
      <span class="value">₹{current_value}</span>
    </div>
    <div class="metric">
      P&amp;L
      <span class="value {pnl_class}">₹{pnl_abs} ({pnl_pct}%)</span>
    </div>
    <div class="metric">
      Invested
      <span class="value">₹{invested}</span>
    </div>
  </div>

  <div class="content">
    {report_html}
  </div>

  <div class="footer">
    Generated by Portfolio Monitor · {generated_at}
  </div>
</div>
</body>
</html>
"""


def _format_inr(val) -> str:
    """Format a number with Indian comma grouping."""
    if val is None:
        return "—"
    try:
        val = float(val)
        sign = "-" if val < 0 else ""
        val = abs(val)
        s = f"{val:,.2f}"
        return f"{sign}{s}"
    except (ValueError, TypeError):
        return str(val)


def send_report(report_markdown: str, portfolio_summary: dict) -> None:
    """Convert markdown report to styled HTML and send via Gmail SMTP."""
    gmail_address = os.environ["GMAIL_ADDRESS"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["RECIPIENT_EMAIL"]

    now = datetime.now()
    month_year = now.strftime("%B %Y")
    generated_at = now.strftime("%d %B %Y, %I:%M %p IST")

    # Convert markdown → HTML
    md_extensions = ["tables", "fenced_code", "nl2br"]
    report_html = markdown.markdown(report_markdown, extensions=md_extensions)

    # Summary values
    current_value = _format_inr(portfolio_summary.get("total_current_value"))
    invested = _format_inr(portfolio_summary.get("total_invested"))
    pnl_abs = _format_inr(portfolio_summary.get("total_unrealized_pnl_abs"))
    pnl_pct = portfolio_summary.get("total_unrealized_pnl_pct", 0)
    pnl_class = "badge-green" if pnl_pct >= 0 else "badge-red"

    full_html = _HTML_TEMPLATE.format(
        month_year=month_year,
        generated_at=generated_at,
        current_value=current_value,
        invested=invested,
        pnl_abs=pnl_abs,
        pnl_pct=f"{pnl_pct:+.2f}",
        pnl_class=pnl_class,
        report_html=report_html,
    )

    # Build email
    subject = (
        f"📊 Portfolio Review — {month_year} "
        f"| ₹{current_value} | {pnl_pct:+.2f}%"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_address
    msg["To"] = recipient

    # Plain‑text fallback
    msg.attach(MIMEText(report_markdown, "plain", "utf-8"))
    # Rich HTML
    msg.attach(MIMEText(full_html, "html", "utf-8"))

    # Send via Gmail SMTP‑SSL
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(gmail_address, gmail_password)
        server.sendmail(gmail_address, recipient, msg.as_string())

    logger.info("Report email sent to %s.", recipient)


def send_failure_notification(error_msg: str) -> None:
    """Send a short failure alert so broken runs don't go unnoticed."""
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient = os.environ.get("RECIPIENT_EMAIL")

    if not all([gmail_address, gmail_password, recipient]):
        logger.error("Cannot send failure email — SMTP env vars missing.")
        return

    now = datetime.now()
    subject = f"⚠️ Portfolio Monitor FAILED — {now.strftime('%d %b %Y')}"
    body = (
        f"The monthly portfolio report failed at {now.isoformat()}.\n\n"
        f"Error:\n{error_msg}\n\n"
        "Check the GitHub Actions log for full details."
    )

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = gmail_address
    msg["To"] = recipient

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(gmail_address, gmail_password)
            server.sendmail(gmail_address, recipient, msg.as_string())
        logger.info("Failure notification sent to %s.", recipient)
    except Exception as exc:
        logger.error("Could not send failure notification: %s", exc)
